### From [TPM conventions](https://pyphi.readthedocs.io/en/latest/conventions.html)

In [1]:
import numpy as np
import pandas as pd
import pyphi
from pyphi.examples import basic_noisy_selfloop_network
import pyphi.TpmClass as tc
import itertools

In [2]:
net = basic_noisy_selfloop_network()
tpm = net.tpm
net

Network([[[[0.271 0.19  0.244]
   [0.919 0.91  0.756]]

  [[0.919 0.91  0.756]
   [0.991 0.99  0.244]]]


 [[[0.919 0.19  0.756]
   [0.991 0.91  0.244]]

  [[0.991 0.91  0.244]
   [0.999 0.99  0.756]]]], cm=[[1 0 1]
 [1 1 1]
 [1 1 1]])

In [3]:
net.node_labels

NodeLabels(('n0', 'n1', 'n2'))

In [4]:
N = len(net.node_labels)
N

3

In [5]:
tpm.shape

(2, 2, 2, 3)

State-by-State form is 2^N x 2^N  (2=number of states per node)

In [6]:
sbn = tpm
sbs = pyphi.convert.sbn2sbs(tpm)
sbs.shape

(8, 8)

In [7]:
n2 = tc.Net(sbs,net.cm, node_labels=net.node_labels)

In [8]:
n2._tpdf

(0, 0, 0)  (0, 0, 1)  (0, 1, 0)  (0, 1, 1)  (1, 0, 0)  (1, 0, 1)  \
(0, 0, 0)   0.446410   0.165950   0.104714   0.038926   0.144080   0.053560   
(0, 0, 1)   0.016009   0.181631   0.003755   0.042605   0.049601   0.562759   
(0, 1, 0)   0.001779   0.020181   0.017985   0.204055   0.005511   0.062529   
(0, 1, 1)   0.000612   0.067428   0.006192   0.681768   0.000198   0.021762   
(1, 0, 0)   0.001779   0.020181   0.017985   0.204055   0.005511   0.062529   
(1, 0, 1)   0.000612   0.067428   0.006192   0.681768   0.000198   0.021762   
(1, 1, 0)   0.000068   0.007492   0.006736   0.741704   0.000022   0.002418   
(1, 1, 1)   0.000002   0.002438   0.000242   0.241318   0.000008   0.007552   

           (1, 1, 0)  (1, 1, 1)  
(0, 0, 0)   0.033796   0.012564  
(0, 0, 1)   0.011635   0.132005  
(0, 1, 0)   0.055725   0.632235  
(0, 1, 1)   0.001998   0.220042  
(1, 0, 0)   0.055725   0.632235  
(1, 0, 1)   0.001998   0.220042  
(1, 1, 0)   0.002174   0.239386  
(1, 1, 1)   0.000748   0.747692

In [9]:
n2._ncdf


n0  n1  n2
n0   1   0   1
n1   1   1   1
n2   1   1   1